### PR TITLE
Fix issues with multi-threaded MKL on mac by disabling it

### LINKED ISSUE #98: Disable use of multi-threaded MKL on mac
Based on the discussions in 

https://github.com/JuliaLang/julia/issues/40787
https://github.com/JuliaLang/julia/issues/43438

It seems the simplest thing may be to not allow multi-threaded MKL on the mac. What would be the easiest way to achieve this?

### PR DESCRIPTION
**Pull request by ViralBShah**
Test case provided by @pablosanjose

### CODE REVIEW

**Comment by KristofferC** [comment]
This doesn't feel acceptable to me at least. It kills the whole point of using the library. It kills the whole library.

**Comment by ViralBShah** [comment]
Huh why? It is only amac issue, and I have yet to add that condition.

**Comment by ViralBShah** [comment]
Something tells me that Intel may not care much about MKL on Mac going forward. ;-)

**Comment by ViralBShah** [comment]
@jishnub The optimized QR getindex tests you added to Julia's LinearAlgebra tests seem to be failing with MKL. See the logs for the failing PRs here. I think approximate equality might make them pass. Does that sound right?

**Comment by ViralBShah** [comment]
I think we may need to revisit doing this on mac.

**Comment by KristofferC** [comment]
This package should almost warn on load time if you are on a mac now that it will run single-threaded and be very slow and should almost surely not be used.

**Comment by ViralBShah** [comment]
A warning is a good idea, but MKL can still be faster single core - depending on what you are doing. Maybe open a separate issue?

**Pull request merged**
