### PR TITLE
add a line of clarification for mainland China users

### LINKED ISSUE #93: Make precompile statements an artifact?
Currently this package downloads the precompile script from Julia GitHub repo via as raw GitHub content which seems to be blocked by GFW in China 

https://github.com/JuliaLinearAlgebra/MKL.jl/blob/d4e61086c4c5f2d6606bb7e0b72cd9cf33ea6068/src/install.jl#L94

As a result we won't be able to mirror this file via the pkg server and pkg storage service so we recently heard some complains on Chinese chat group about this. I'm wondering if we could make it as an artifact or maybe the precompile script can be shipped with Julia itself?

### PR DESCRIPTION
**Pull request by Roger-luo**
just add an explicit instruction regarding to the internet issue for users from mainland China, this should close #93

### CODE REVIEW

**Comment by Roger-luo** [comment]
@ViralBShah the test failure seems unrelated since I just changed the README. 

I'm wondering if this specific instruction would be Ok to have in the README?

**Comment by ViralBShah** [comment]
Rather than saying it is for users in China, can we say it is for users where GitHub raw content is blocked?

**Comment by Roger-luo** [comment]
I changed it to  kept the Chinese version of that instruction since I feel this issue is probably mostly happens for Chinese users...

**Comment by ViralBShah** [comment]
Yikes - no idea why CI is so broken all of a sudden. Anyways, this should have nothing to do with it.

**Pull request merged**
