### PR TITLE
Remove manual mapping of non-suffixed APIs, which is fixed in MKL 2024.1

### PR DESCRIPTION
**Pull request by ViralBShah**
Discussion in https://github.com/JuliaLinearAlgebra/MKL.jl/pull/140#issuecomment-2110250127.

Bumping to 2024.1 will also drop support for MKL on Mac, and threading tests fail on Julia 1.8. As a result Julia 1.9 is the new minimum. As a result, bumping the version to 0.7.

cc @amontoison

### CODE REVIEW

**Comment by ViralBShah** [comment]
I suppose I should just go ahead and remove macOS-13 from CI, since we no longer have support for macs. It would be nice if it just ended up with MKL_jll not available (like on macOS-14) rather than the Pkg error we get now.

**Comment by giordano** [comment]
We can have a step which installs an older MKL_jll for macos-13.

**Comment by ViralBShah** [comment]
> We can have a step which installs an older MKL_jll for macos-13.

Those won't have the `dlamch_64` etc. that only got done in 2024.1. I think folks who want Intel Macs may be best off using an older version of MKL.jl. Is there a way to make that happen?

**Comment by ViralBShah** [comment]
What is the easiest way to get an IPOPT test in this package that will test the LP64 interface? Could I request you to add a test to this PR or point me to an example?

**Comment by ViralBShah** [comment]
We should probably add a couple of simple LP64 BLAS tests to make sure we don't regress.

**Pull request merged**
