### PR TITLE
[Do not merge] Test for MKL 2022.2

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by giordano** [comment]
Do you need to do this? It's already compatible with 2022.2

**Comment by ViralBShah** [comment]
So, just depend on the resolver to pick the latest version of MKL_jll? I suppose that would work. I can avoid merging this - but use it to run the tests.

**Comment by giordano** [comment]
Yes, unless you need to say "I want to use _only_ 2022.2 and above because 2022.1 is broken" the resolver will pick up 2022.2 if available

**Comment by ViralBShah** [comment]
Should re-run this once MKL_jll 2022.2 is available in the registry.

**Pull request closed without merging**
