### PR TITLE
transition to only supporting Julia 1.7+

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Failing tests are not related to this PR.

**Comment by giordano** [comment]
[`src/install.jl`](https://github.com/JuliaLinearAlgebra/MKL.jl/blob/3120aa038382f5e2a54044c9e10596c22c0f4a00/src/install.jl) should have been deleted?  The README should also be updated to remove references to Julia v1.6

**Comment by KristofferC** [comment]
I was sure I deleted that... Must have forgotten to `git add` it or something. I'll make a follow up PR.

**Comment by ViralBShah** [comment]
I already deleted on master

**Pull request merged**
