### PR TITLE
[Do not merge] Use the new LBT mechanism introduced in Julia to forward to MKL

### PR DESCRIPTION
**Pull request by ViralBShah**
I suppose we should only merge this upon releasing Julia 1.7.

- Build 1.7 master
- `Pkg.add(url="git@github.com:JuliaLinearAlgebra/MKL.jl", rev="lbt")`
- `using MKL`
- `Pkg.test("MKL")`
 
This will replace OpenBLAS with MKL (and is the same procedure for another BLAS). The tests pass on mac, but not on linux. Can someone review if my modifications here are all good?

### CODE REVIEW

**Comment by ViralBShah** [comment]
cc @KristofferC @andreasnoack

**Comment by ViralBShah** [comment]
I suppose `libblastrampoline_jll` is not really required in the Project.toml.

**Comment by ViralBShah** [comment]
I don't think the tests work right on linux.

**Comment by ViralBShah** [comment]
Should fix #46

**Comment by giordano** [comment]
> Should fix #46

Are you sure?

**Comment by ViralBShah** [comment]
> > Should fix #46
> 
> Are you sure?

We now unconditionally use only the `64_` suffixed symbols on 64-bit setups. Internally, LBT forwards those to the regular BLAS symbols for ILP64 BLAS in MKL. But I guess that could lead to 32-bit and 64-bit MKL loaded simultaneously and break. I'm not so sure anymore.

I think if you want to use LP64 BLAS on 64-bit systems, most likely the system image needs to be rebuilt. Help appreciated - if people can try things out.

**Comment by KristofferC** [comment]
Got something weird on my Mac:

```
julia> using LinearAlgebra

julia> @edit LinearAlgebra.BLAS.vendor()

julia> using MKL

julia> @edit LinearAlgebra.BLAS.vendor() # infinite segfaults
```

not sure what is going on. Can anyone repro?

**Comment by ViralBShah** [comment]
Yes, getting the same segfaults.

**Comment by KristofferC** [comment]
But other than that, it seems to work quite well.

**Pull request closed without merging**
